// <auto-generated />
using System;
using LionBitcoin.Wallet.Cli.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LionBitcoin.Wallet.Cli.Persistence.Migrations
{
    [DbContext(typeof(LionBitcoinDbContext))]
    partial class LionBitcoinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LionBitcoin.Wallet.Cli.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AccountPrivateKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DepositAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedTime")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_wallets_created_at_index");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
