// <auto-generated />
using System;
using LionBitcoin.Service.Wallet.Client.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LionBitcoin.Service.Wallet.Client.Persistence.Migrations
{
    [DbContext(typeof(WalletClientDbContext))]
    [Migration("20260330172220_DepositAddressMigration")]
    partial class DepositAddressMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LionBitcoin.Service.Wallet.Client.Domain.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccountPrivateKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("account_private_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DepositAddress")
                        .IsRequired()
                        .HasMaxLength(62)
                        .HasColumnType("character varying(62)")
                        .HasColumnName("deposit_address");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_wallets_created_at_index")
                        .HasDatabaseName("ix_wallets_created_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "CreatedAt" }, "ix_wallets_created_at_index"), "brin");

                    b.ToTable("wallets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
