// <auto-generated />
using System;
using LionBitcoin.Service.Wallet.Client.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LionBitcoin.Service.Wallet.Client.Persistence.Migrations
{
    [DbContext(typeof(WalletClientDbContext))]
    [Migration("20260331085501_AddLastSyncTimeInWallet")]
    partial class AddLastSyncTimeInWallet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LionBitcoin.Service.Wallet.Client.Domain.Entities.Utxo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("BlockHeight")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("OutputIndex")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_utxos_created_at_index");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "CreatedAt" }, "ix_utxos_created_at_index"), "brin");

                    b.ToTable("Utxos");
                });

            modelBuilder.Entity("LionBitcoin.Service.Wallet.Client.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AccountPrivateKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DepositAddress")
                        .IsRequired()
                        .HasMaxLength(62)
                        .HasColumnType("character varying(62)");

                    b.Property<DateTimeOffset?>("LastSyncedTime")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_wallets_created_at_index");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "CreatedAt" }, "ix_wallets_created_at_index"), "brin");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("LionBitcoin.Service.Wallet.Client.Domain.Entities.Utxo", b =>
                {
                    b.HasOne("LionBitcoin.Service.Wallet.Client.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Utxos")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("LionBitcoin.Service.Wallet.Client.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Utxos");
                });
#pragma warning restore 612, 618
        }
    }
}
